# Generated by Django 4.1.3 on 2022-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_id', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('temperatures', models.JSONField()),
            ],
        ),
    ]
