# Generated by Django 4.1.3 on 2022-11-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0002_alter_weather_weather_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
    ]
