# Generated by Django 4.1.3 on 2022-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0003_remove_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
